### ISSUE TITLE
Unexpectedly high GPU usage?

### ISSUE THREAD

**Issue by floral-qua-floral** [ToadsworthLP/desktoptale#8] opened 2024-05-14 02:35 UTC
I've noticed that when running Desktoptale, my resting GPU usage increases from 0-3%, all the way up to around 60%. The testing was performed by simply launching and closing Desktoptale while watching the Task Manager, without any other GPU-intensive programs running, and the changes were immediate when the program started or stopped. Only one character was present at a time for the testing.

The majority of the GPU usage is attributed to Desktop Window Manager, which typically rests at 0.1-0.3% GPU usage when idle. Desktoptale is second, with a little bit less usage than Desktop Window Manager. Client Server Runtime Process is also increased to a less significant extent, but still increases a fair distance past its consistent resting GPU usage of 0.1%. Here is a screenshot of the four processes using the most GPU while Desktoptale is running:
![image](https://github.com/ToadsworthLP/desktoptale/assets/49110090/8c6fbfb6-d994-4631-b8d1-4d6a3da47293)

Some details that may be relevant:
* This is on a laptop running Windows 10.
* GPU 0 - 3D is the integrated graphics card.
* A second monitor is connected. When it's disconnected, Desktoptale's GPU impact seems to be reduced by about half. Notably, the character was only ever present on the primary, built-in screen for these tests.

Here is a screenshot of the GPU usage when the second monitor is disconnected:
![image](https://github.com/ToadsworthLP/desktoptale/assets/49110090/af0b1968-a55f-49a0-8f80-b4f2c0eeab50)

Here is a screenshot of the GPU usage when Desktoptale is set to run on the high-performance graphics card (with the second monitor re-connected). It seems like the GPU usage of Desktoptale itself and Client Server Runtime Process decrease dramatically, while Desktop Window Manager's GPU usage is increased by the same amount:
![image](https://github.com/ToadsworthLP/desktoptale/assets/49110090/fb36b2f8-e93a-4059-bd39-f831c32d2fad)

Lastly - and I do apologize for including like a million screenshots of Task Manager, but this seemed like it could be particularly useful - during this testing, I noticed that, while the confirmation dialog for enabling Click-Through Mode is open, Desktoptale's total GPU impact drops to near zero. However, once the confirmation dialog is closed, the GPU usage goes back up; whether or not Click-Through Mode is enabled has no effect. I suspect that this must be because characters are frozen while this dialog box is open.
![image](https://github.com/ToadsworthLP/desktoptale/assets/49110090/4ad920e6-b023-4eb4-9238-324494940cd8)

The last observation in particular makes me wonder if it would be possible to significantly improve performance by freezing character rendering in a similar way whenever all characters are standing still. Putting that aside though, it does seem strange to me that Desktoptale would cause such high GPU usage in general. I don't have any experience with doing stuff like what this program does, though, so if it's just because it's inherently expensive to draw stuff outside of any window, I wouldn't be all that surprised.

**Comment by ToadsworthLP** [comment] 2024-05-31 21:37
Since 1.4.0, all characters get rendered into one big window that spans all connected monitors since the previous approach (one window per character) caused a number of weird issues with more than just a handful of characters on screen. However, iGPUs sometimes struggle with big render surfaces, so that's what's causing the behavior you're seeing. You're 100% correct in your assumption about the dialogue window - it freezes rendering of the big window which causes GPU usage to drop. Since this is caused by intended behavior, I'll close this as resolved, but thank you nonetheless for the thorough investigation!

**Closed** 2024-05-31 21:37 UTC
